import type { components } from '../../api/generado/esquema'

export const bitacoraDeEjemplo = [
  {
    id: 'evt-6',
    tipo: 'CORTE_RESTABLECIDO',
    sectorId: 'bocagrande',
    corteId: 'corte-101',
    timestamp: '2026-09-25T19:30:00Z',
    descripcion: 'Servicio restablecido en Bocagrande tras mantenimiento preventivo en la red matriz',
    estado: 'CON_SERVICIO',
    urlOriginal: undefined,
    imagenUrl: undefined,
    cantidadReportesSustento: 0,
  },
  {
    id: 'evt-5',
    tipo: 'CORTE_CONFIRMADO_POR_CIUDADANOS',
    sectorId: 'torices',
    corteId: undefined,
    timestamp: '2026-09-25T17:30:00Z',
    descripcion: 'Consenso de reportes vecinales confirma interrupción del suministro en Torices',
    estado: 'SIN_SERVICIO',
    urlOriginal: undefined,
    imagenUrl: undefined,
    cantidadReportesSustento: 5,
  },
  {
    id: 'evt-4',
    tipo: 'CORTE_DETECTADO_POR_INGESTA',
    sectorId: 'getsemani',
    corteId: undefined,
    timestamp: '2026-09-25T16:00:00Z',
    descripcion: 'Aviso detectado automáticamente por avería súbita en calle de San Juan',
    estado: 'SIN_SERVICIO',
    urlOriginal: 'https://www.acuacar.com/noticias/ejemplo-corte-getsemani',
    imagenUrl: 'https://www.acuacar.com/media/ejemplo-boletin-getsemani.jpg',
    cantidadReportesSustento: 0,
  },
  {
    id: 'evt-3',
    tipo: 'CORTE_ANUNCIADO',
    sectorId: 'centro',
    corteId: 'corte-102',
    timestamp: '2026-09-25T12:00:00Z',
    descripcion: 'Aviso de corte programado para instalación de macro-medidores',
    estado: 'CORTE_PROGRAMADO',
    urlOriginal: 'https://www.acuacar.com/comunicados/ejemplo-corte-centro',
    imagenUrl: undefined,
    cantidadReportesSustento: 0,
  },
  {
    id: 'evt-2',
    tipo: 'CORTE_ANUNCIADO',
    sectorId: undefined,
    corteId: undefined,
    timestamp: '2026-09-25T09:00:00Z',
    descripcion: 'Trabajos generales de mantenimiento eléctrico en la planta de tratamiento El Bosque',
    estado: undefined,
    urlOriginal: undefined,
    imagenUrl: undefined,
    cantidadReportesSustento: 0,
  },
  {
    id: 'evt-1',
    tipo: 'CORTE_RESTABLECIDO',
    sectorId: 'canapote',
    corteId: 'corte-100',
    timestamp: '2026-09-24T14:00:00Z',
    descripcion: 'Servicio restablecido con baja presión en Canapote mientras normaliza la red',
    estado: 'PRESION_BAJA',
    urlOriginal: undefined,
    imagenUrl: undefined,
    cantidadReportesSustento: 0,
  },
] satisfies components['schemas']['EventoBitacoraRespuesta'][]

export const cumplimientoDeEjemplo = {
  sectorId: undefined,
  duracionPrometidaSegundos: 36_000,
  duracionRealSegundos: 45_000,
  desviacionSegundos: 9000,
  porcentajeCumplimiento: 80,
} satisfies components['schemas']['IndiceCumplimientoRespuesta']

export const cumplimientoDecimalDeEjemplo = {
  sectorId: undefined,
  duracionPrometidaSegundos: 28_800,
  duracionRealSegundos: 43_200,
  desviacionSegundos: 14_400,
  porcentajeCumplimiento: 66.67,
} satisfies components['schemas']['IndiceCumplimientoRespuesta']

export const serieDeEjemplo = [
  {
    periodo: '2026-04',
    duracionPrometidaSegundos: 72_000,
    duracionRealSegundos: 64_800,
    desviacionSegundos: -7200,
    porcentajeCumplimiento: 100,
    cantidadCortes: 4,
  },
  {
    periodo: '2026-05',
    duracionPrometidaSegundos: 36_000,
    duracionRealSegundos: 40_000,
    desviacionSegundos: 4000,
    porcentajeCumplimiento: 90,
    cantidadCortes: 1,
  },
  {
    periodo: '2026-06',
    duracionPrometidaSegundos: 108_000,
    duracionRealSegundos: 120_000,
    desviacionSegundos: 12_000,
    porcentajeCumplimiento: 90,
    cantidadCortes: 6,
  },
  {
    periodo: '2026-07',
    duracionPrometidaSegundos: 90_000,
    duracionRealSegundos: 108_000,
    desviacionSegundos: 18_000,
    porcentajeCumplimiento: 83.3,
    cantidadCortes: 5,
  },
  {
    periodo: '2026-08',
    duracionPrometidaSegundos: 144_000,
    duracionRealSegundos: 160_000,
    desviacionSegundos: 16_000,
    porcentajeCumplimiento: 90,
    cantidadCortes: 8,
  },
  {
    periodo: '2026-09',
    duracionPrometidaSegundos: 80_000,
    duracionRealSegundos: 100_000,
    desviacionSegundos: 20_000,
    porcentajeCumplimiento: 80,
    cantidadCortes: 4,
  },
] satisfies components['schemas']['PuntoSerieRespuesta'][]

export const estadisticasDeEjemplo = {
  sectoresMasAfectados: [
    { sectorId: 'torices', nombre: 'TORICES', cantidadCortes: 8 },
    { sectorId: 'getsemani', nombre: 'GETSEMANI', cantidadCortes: 5 },
    { sectorId: 'bocagrande', nombre: 'BOCAGRANDE', cantidadCortes: 3 },
  ],
  cortesPorDiaDeSemana: {
    Jueves: 4,
    Lunes: 2,
    Domingo: 0,
    Miércoles: 7,
    Viernes: 5,
    Martes: 3,
    Sábado: 1,
  },
  duracionPromedioHoras: 5.4,
} satisfies components['schemas']['EstadisticasRespuesta']
